# Generated by Django 3.2.14 on 2023-02-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('instructions', models.TextField(blank=None, default=None, null=True)),
            ],
            options={
                'db_table': 'api_cocktail',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=10, null=True)),
                ('measurement', models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('cube', 'Cube'), ('cup', 'Cup'), ('dash', 'Dash'), ('drop', 'Drop'), ('jigger', 'Jigger'), ('leaf', 'Leaf'), ('liter', 'Liter'), ('milliliter', 'Milliliter'), ('ounce', 'Ounce'), ('part', 'Part'), ('peel', 'Peel'), ('pint', 'Pint'), ('pound', 'Pound'), ('quart', 'Quart'), ('rind', 'Rind'), ('scoop', 'Scoop'), ('slice', 'Slice'), ('splash', 'Splash'), ('spear', 'Spear'), ('spiral', 'Spiral'), ('sprig', 'Sprig'), ('sprinkle', 'Sprinkle'), ('stalk', 'Stalk'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('to taste', 'To Taste'), ('twist', 'Twist'), ('wedge', 'Wedge'), ('wheel', 'Wheel'), ('whole', 'Whole'), ('white', 'White'), ('yolk', 'Yolk'), ('zest', 'Zest')], default=None, max_length=20, null=True)),
                ('preparation', models.CharField(blank=True, choices=[('broken in half', 'Broken In Half'), ('broken up', 'Broken Up'), ('chilled', 'Chilled'), ('chopped canned', 'Chopped Canned'), ('cored', 'Cored'), ('cut in pieces', 'Cut In Pieces'), ('hollowed out', 'Hollowed Out'), ('hot', 'Hot'), ('thinly pared', 'Thinly Pared'), ('thinly sliced', 'Thinly Sliced'), ('sliced', 'Sliced'), ('juiced', 'Juiced'), ('grated', 'Grated'), ('ground', 'Ground'), ('warmed', 'Warmed')], default=None, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Cocktail Ingredient',
                'verbose_name_plural': 'Cocktail Ingredients',
                'db_table': 'api_cocktailingredient',
                'ordering': ('ingredient__name', 'amount', 'measurement'),
            },
        ),
        migrations.CreateModel(
            name='ControlledBeverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_in_stock', models.BooleanField(default=False, null=True)),
            ],
            options={
                'verbose_name': 'Controlled Beverage',
                'verbose_name_plural': 'Controlled Beverages',
                'db_table': 'api_controlledbeverage',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('is_controlled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_ingredient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField(blank=True, db_column='date', null=True)),
                ('name', models.CharField(max_length=250)),
                ('ext_calapi_inadiutorium_season', models.CharField(blank=True, choices=[('ordinary', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('easter', 'Easter')], max_length=9, null=True)),
                ('cocktails', models.ManyToManyField(blank=True, default=None, to='api.Cocktail')),
            ],
            options={
                'db_table': 'api_feast',
                'ordering': ['_date'],
            },
        ),
    ]
