# Generated by Django 3.2.14 on 2023-02-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('ext_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feast',
            name='ext_calapi_inadiutorium_celebration',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feast', to='ext_data.calapiinadiutoriumcelebration'),
        ),
        migrations.AddField(
            model_name='controlledbeverage',
            name='ingredients',
            field=models.ManyToManyField(blank=True, default=None, to='api.Ingredient'),
        ),
        migrations.AddField(
            model_name='cocktailingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient'),
        ),
        migrations.AddField(
            model_name='cocktail',
            name='ingredients',
            field=models.ManyToManyField(to='api.CocktailIngredient'),
        ),
    ]
