# Generated by Django 3.2.14 on 2023-04-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230403_1402'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cocktailingredient',
            options={'ordering': ('ingredient__name', '_amount', '_measurement'), 'verbose_name': 'Cocktail Ingredient', 'verbose_name_plural': 'Cocktail Ingredients'},
        ),
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='amount',
            new_name='_amount',
        ),
        migrations.RenameField(
            model_name='cocktailingredient',
            old_name='measurement',
            new_name='_measurement',
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='_amount',
            field=models.DecimalField(blank=True, db_column='amount', decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cocktailingredient',
            name='_measurement',
            field=models.CharField(blank=True, choices=[('bottle', 'Bottle'), ('cube', 'Cube'), ('cup', 'Cup'), ('dash', 'Dash'), ('drop', 'Drop'), ('jigger', 'Jigger'), ('leaf', 'Leaf'), ('liter', 'Liter'), ('milliliter', 'Milliliter'), ('ounce', 'Ounce'), ('part', 'Part'), ('peel', 'Peel'), ('pint', 'Pint'), ('pound', 'Pound'), ('quart', 'Quart'), ('rind', 'Rind'), ('scoop', 'Scoop'), ('slice', 'Slice'), ('splash', 'Splash'), ('spear', 'Spear'), ('spiral', 'Spiral'), ('sprig', 'Sprig'), ('sprinkle', 'Sprinkle'), ('stalk', 'Stalk'), ('tablespoon', 'Tablespoon'), ('teaspoon', 'Teaspoon'), ('to taste', 'To Taste'), ('twist', 'Twist'), ('wedge', 'Wedge'), ('wheel', 'Wheel'), ('whole', 'Whole'), ('white', 'White'), ('yolk', 'Yolk'), ('zest', 'Zest')], db_column='measurement', default=None, max_length=20, null=True),
        ),
    ]
