# Generated by Django 3.2.14 on 2023-02-01 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalapiInadiutoriumCelebration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('title', models.CharField(max_length=500, null=True)),
                ('colour', models.CharField(choices=[('green', 'Green'), ('violet', 'Violet'), ('white', 'White'), ('red', 'Red')], max_length=6)),
                ('rank', models.CharField(max_length=255)),
                ('rank_num', models.FloatField()),
            ],
            options={
                'ordering': ('rank_num',),
            },
        ),
        migrations.CreateModel(
            name='LidlProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('ext_id', models.IntegerField(unique=True)),
                ('url', models.CharField(max_length=1855)),
            ],
            options={
                'verbose_name': 'Lidl Product',
                'verbose_name_plural': 'Lidl Products',
            },
        ),
        migrations.CreateModel(
            name='LidlProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pull_date', models.DateTimeField(verbose_name='date of price pull')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext_data.lidlproduct')),
            ],
            options={
                'verbose_name': 'Lidl Product Price',
                'verbose_name_plural': 'Lidl Product Prices',
            },
        ),
        migrations.CreateModel(
            name='CalapiInadiutoriumLiturgicalDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='create_date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='modified_date')),
                ('date', models.DateField()),
                ('season', models.CharField(choices=[('ordinary', 'Ordinary Time'), ('advent', 'Advent'), ('christmas', 'Christmas'), ('lent', 'Lent'), ('easter', 'Easter')], max_length=9)),
                ('season_week', models.IntegerField()),
                ('weekday', models.CharField(choices=[('sunday', 'Sunday'), ('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=9)),
                ('celebrations', models.ManyToManyField(related_name='liturgical_days', to='ext_data.CalapiInadiutoriumCelebration')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='ABCProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('url', models.CharField(max_length=1855)),
                ('avg_price_per_liter', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_per_liter', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_50_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_100_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_118_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_200_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_375_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_473_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_473_18_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_750_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_1_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_1_5_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('best_price_1_75_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_50_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_100_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_118_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_200_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_375_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_473_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_473_18_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_750_ml', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_1_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_1_5_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('avg_price_1_75_l', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('controlled_beverage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.controlledbeverage')),
            ],
            options={
                'verbose_name': 'ABC Product',
                'verbose_name_plural': 'ABC Products',
            },
        ),
        migrations.CreateModel(
            name='ABCPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(default=None, max_length=250, null=True)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, default=None, max_digits=10, null=True)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('is_on_sale', models.BooleanField(default=False)),
                ('pull_date', models.DateTimeField(verbose_name='date of price pull')),
                ('product_size', models.IntegerField(default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ext_data.abcproduct')),
            ],
        ),
    ]
