# Generated by Django 3.2.14 on 2023-05-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_controlledbeverage_ingredients'),
        ('ext_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='ext_data.abcproduct'),
        ),
        migrations.AlterField(
            model_name='abcproduct',
            name='controlled_beverage',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='abc_product', to='api.controlledbeverage'),
        ),
    ]
