# Generated by Django 3.2.14 on 2023-07-31 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ext_data', '0002_auto_20230512_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcproduct',
            name='avg_price_700_ml',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='abcproduct',
            name='best_price_700_ml',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
